---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/hmariset/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-crossplane-KFLUXVNGD-88
